# Generated by Django 3.1.7 on 2021-03-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
