# Generated by Django 3.1.7 on 2021-03-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210302_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='birthdate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='zodiac',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
